### ISSUE TITLE
A few more building errors

### ISSUE THREAD

**Issue by yangky11** [zhangir-azerbayev/ProofNet#10]
Hi Zhangir,

I ran the fixed code and got the following errors:
```
/home/kaiyu/ProofNet/benchmark/benchmark_to_publish/formal/Axler.lean:107:28: error: unexpected token
/home/kaiyu/ProofNet/benchmark/benchmark_to_publish/formal/Axler.lean:115:14: error: unexpected token
/home/kaiyu/ProofNet/benchmark/benchmark_to_publish/formal/Axler.lean:120:2: error: unexpected token
```

It looks like the notation `∥` is not available?

**Comment by zhangir-azerbayev** [comment]
The issue is the difference between the ∥ (U+2225) character and the ‖ (U+2016) character. Mathlib switched from the former to the latter during the development of the benchmark. Merging a PR to fix.

**Comment by zhangir-azerbayev** [comment]
Fixed in https://github.com/zhangir-azerbayev/ProofNet/pull/11

**Comment by zhangir-azerbayev** [comment]
verified that `lean --make benchmark` works modulo sorrys.
