### ISSUE TITLE
mistakes in proofnet.png?

### ISSUE THREAD

**Issue by abliss** [zhangir-azerbayev/ProofNet#19]
Hi, I just browsed to the front of this repo, and I'm very confused by the example image proofnet.png . Is it meant to be an example of a mistaken proof generated by a bad model? It seems to me that the statement is about a group of size 312 but the proof is about a group of size 351? But also, that proof seems to think that 351/13 is 9 when it's actually 27?
If these errors are intentional, maybe it would be good to frame the image with a bit more context, to avoid bewildering future casual browsers of the repo.

**Comment by zhangir-azerbayev** [comment]
This was indeed a mistake. Thanks for catching it.
