### ISSUE TITLE
Dummit and Foote Chapter 1 

### ISSUE THREAD

**Issue by zhangir-azerbayev** [zhangir-azerbayev/ProofNet#2]
Criteria by which problems are excluded: 
1. Rely on unformalized (within the text) geometric notions. 
2. Are open-ended (e.g calculate...) 
3. Require concepts not formalized in mathlib 

Goal is to get 100 problems of Dummit and Foote. 

The following exercises look especially promising: 

1.1 15, 16, 17, 20, 22, 25, 29, 30, 34, 
1.3 11, 13
1.6 11, 17, 23
1.7 5, 6 

Stuff that requires showing something is a structure: not quite sure how to approach these
1.1

**Comment by ksmzzang2003** [comment]
Is it third edition? I want to contibute this project.

**Comment by zhangir-azerbayev** [comment]
this got done a long time ago.
