### ISSUE TITLE
2 is not irrational

### ISSUE THREAD

**Issue by eric-wieser** [zhangir-azerbayev/ProofNet#5]
This statement is false:

https://github.com/zhangir-azerbayev/ProofNet/blob/00cd47d4d692e8af78990803dcca8dc387cde0ed/benchmark/benchmark_to_publish/formal/Cambridge-Tripos.lean#L9-L10

because `2^(1/3) + 3^(1/3) = 2^0 + 3^0 = 1 + 1 = 2`.

**Comment by BartoszPiotrowski** [comment]
Thank you, should be fixed now.

**Comment by zhangir-azerbayev** [comment]
Thanks Eric! This kind of error also resulted in an incorrect formalization of an IMO problem in minif2f. See figure 14 on page 30 of https://arxiv.org/abs/2205.11491.
